sudo: required
language: python

services:
  - docker

python:
  - "3.5"

jobs:
  include:
    - stage: lint
      install:
        - pip install -U flake8 flake8-import-order
      script:
        - flake8 baricadr tests --ignore=E501
    - stage: test
      python: '3.5'
      install:
        - sudo service postgresql stop
        - cp local.example.cfg local.cfg
        - docker-compose build
        - docker-compose up -d
        - sleep 15 # Wait for the container to be ready
        - docker-compose logs
      script:
        - docker-compose exec baricadr pytest -v --log-cli-level debug
    - stage: test
      python: '3.6'
      install:
        - sudo service postgresql stop
        - cp local.example.cfg local.cfg
        - docker-compose build
        - docker-compose up -d
        - sleep 15 # Wait for the container to be ready
        - docker-compose logs
      script:
        - docker-compose exec baricadr pytest -v --log-cli-level debug
