# This is a development docker-compose.yml, don't use this one in production
version: "3.7"

x-baricadr-variables: &baricadr-variables
    BARICADR_RUN_MODE: "dev"
    BARICADR_REPOS_CONF: "test-data/sample_repos.yml"
    TZ: "Etc/UTC"
    CELERYD_CONCURRENCY: 3


services:
    baricadr:
        build: ./
        ports:
            - 9100:80
        depends_on:
            - redis
            - db
        environment: *baricadr-variables
        volumes:
            - ./test-data/test-fs-mountpoint/:/repos/
            - ./:/baricadr/
            - ./docker/uwsgi_dev.ini:/etc/uwsgi/uwsgi.ini:ro
            - task_logs:/var/log/baricadr/tasks/
            # This adds an HTTP basic auth, with a preconfigured account: login=baricadr password=baricadr
            - ./docker/nginx_baricadr_auth.conf:/etc/nginx/conf.d/nginx_baricadr.conf:ro
            - ./docker/htpasswd_user:/etc/nginx/conf.d/htpasswd_user:ro

    worker:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        depends_on:
            - redis
            - db
        entrypoint: python3
        command: /opt/celery_dev_launch.py
        environment: *baricadr-variables
        volumes:
            - ./test-data/test-fs-mountpoint/:/repos/
            - ./:/baricadr/:ro
            - ./docker_celery/celery_dev_launch.py:/opt/celery_dev_launch.py:ro
            - task_logs:/var/log/baricadr/tasks/

    monitor:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        ports:
            - "5555:5555"
        entrypoint: celery
        command: flower -A baricadr.tasks.celery --port=5555 --loglevel=info --autoreload
        depends_on:
            - redis
        environment: *baricadr-variables
        volumes:
            - ./:/baricadr/:ro

    redis:
        image: redis:4.0

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"

    # An SFTP server for tests
    sftp:
        image: atmoz/sftp
        command: foo:pass:1001
        volumes:
            - ./test-data/test-repo/:/home/foo/test-repo/:ro
            - ./test-data/test-repo-sftp/:/home/foo/test-repo-sftp/:ro

    # An S3 server for tests
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
          MINIO_ACCESS_KEY: admin
          MINIO_SECRET_KEY: password
        command: server /data

    # An S3 client to bootstrap the S3 server
    minioc:
        image: minio/mc
        stdin_open: true
        tty: true
        entrypoint: "/bin/sh"
        volumes:
            - ./test-data/test-repo/:/test-repo/:ro
            - ./test-data/test-repo-sftp/:/test-repo-sftp/:ro

    db:
        image: postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: postgres

volumes:
    # A volume shared between baricadr app and worker
    task_logs:
