"""rework db model

Revision ID: 0296d30b2db8
Revises: 4798b5ed58de
Create Date: 2020-10-28 10:57:03.960798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0296d30b2db8'
down_revision = '4798b5ed58de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_baricadr_task_path', table_name='baricadr_task')
    op.create_index(op.f('ix_baricadr_task_path'), 'baricadr_task', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baricadr_task_path'), table_name='baricadr_task')
    op.create_index('ix_baricadr_task_path', 'baricadr_task', ['path'], unique=True)
    # ### end Alembic commands ###
