"""rework db model

Revision ID: 4798b5ed58de
Revises: b5a2bc3b5a9c
Create Date: 2020-10-28 10:19:21.259804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4798b5ed58de'
down_revision = 'b5a2bc3b5a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baricadr_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baricadr_task_path'), 'baricadr_task', ['path'], unique=True)
    op.create_index(op.f('ix_baricadr_task_task_id'), 'baricadr_task', ['task_id'], unique=True)
    op.create_index(op.f('ix_baricadr_task_type'), 'baricadr_task', ['type'], unique=False)
    op.drop_index('ix_pull_task_path', table_name='pull_task')
    op.drop_index('ix_pull_task_task_id', table_name='pull_task')
    op.drop_table('pull_task')
    op.drop_index('ix_freeze_task_path', table_name='freeze_task')
    op.drop_index('ix_freeze_task_task_id', table_name='freeze_task')
    op.drop_table('freeze_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freeze_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='freeze_task_pkey')
    )
    op.create_index('ix_freeze_task_task_id', 'freeze_task', ['task_id'], unique=True)
    op.create_index('ix_freeze_task_path', 'freeze_task', ['path'], unique=True)
    op.create_table('pull_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pull_task_pkey')
    )
    op.create_index('ix_pull_task_task_id', 'pull_task', ['task_id'], unique=True)
    op.create_index('ix_pull_task_path', 'pull_task', ['path'], unique=True)
    op.drop_index(op.f('ix_baricadr_task_type'), table_name='baricadr_task')
    op.drop_index(op.f('ix_baricadr_task_task_id'), table_name='baricadr_task')
    op.drop_index(op.f('ix_baricadr_task_path'), table_name='baricadr_task')
    op.drop_table('baricadr_task')
    # ### end Alembic commands ###
