"""added freeze_task

Revision ID: b5a2bc3b5a9c
Revises: de615f71c504
Create Date: 2020-10-26 10:58:53.117758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a2bc3b5a9c'
down_revision = 'de615f71c504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freeze_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freeze_task_path'), 'freeze_task', ['path'], unique=True)
    op.create_index(op.f('ix_freeze_task_task_id'), 'freeze_task', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freeze_task_task_id'), table_name='freeze_task')
    op.drop_index(op.f('ix_freeze_task_path'), table_name='freeze_task')
    op.drop_table('freeze_task')
    # ### end Alembic commands ###
